sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 162278

  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tNxR8kHuLWFaFm4bmVp
    access-key-secret: N9krsMGMqtFoKUIDhbTCvvXmc7LU2w
    bucket-name: practical-projects

  redis:
    host: localhost
    port: 6379
    password: 162278
    #数据库：有0-15共16个，默认0
    database: 0